# Make rules for configuration files.
#
# $Id$

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-i686.config $(CFG)-i686-debug.config \
	$(CFG)-i686-PAE.config $(CFG)-i686-PAEdebug.config \
	$(CFG)-x86_64.config $(CFG)-x86_64-debug.config \
	$(CFG)-s390x.config \
	$(CFG)-armv7hl.config $(CFG)-armv7hl-lpae.config \
	$(CFG)-aarch64.config \
	$(CFG)-ppc.config $(CFG)-ppc-smp.config \
	$(CFG)-ppc64.config $(CFG)-ppc64p7.config $(CFG)-ppc64-debug.config 

PLATFORMS	= x86 x86_64 powerpc powerpc32 powerpc64 s390x arm arm64
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

temp-generic: config-generic
	cat config-generic config-nodebug > temp-generic

temp-debug-generic: config-generic
	cat config-generic config-debug > temp-debug-generic

temp-arm-generic: config-arm-generic temp-generic
	perl merge.pl $^ > $@

temp-armv7-generic: config-armv7-generic temp-arm-generic
	perl merge.pl $^ > $@

temp-armv7: config-armv7 temp-armv7-generic
	perl merge.pl $^ > $@

temp-armv7-lpae: config-armv7-lpae temp-armv7-generic
	perl merge.pl $^ > $@

temp-arm-debug-generic: temp-arm-generic temp-debug-generic
	perl merge.pl $^ > $@

temp-arm64: config-arm64 temp-arm-generic
	perl merge.pl $^ > $@

temp-arm64-debug: config-arm64 temp-arm-debug-generic
	perl merge.pl $^ > $@

temp-x86-32: config-x86-32-generic config-x86-generic
	perl merge.pl $^  > $@

temp-x86-32-generic: temp-x86-32 temp-generic
	perl merge.pl $^  > $@

temp-x86-debug-generic: temp-x86-32 temp-debug-generic
	perl merge.pl $^  > $@

temp-x86-64: config-x86_64-generic config-x86-generic
	perl merge.pl $^  > $@

temp-x86_64-generic: temp-x86-64 temp-generic
	perl merge.pl $^  > $@

temp-x86_64-debug-generic: temp-x86-64 temp-debug-generic
	perl merge.pl $^  > $@

temp-powerpc-generic: config-powerpc-generic temp-generic
	perl merge.pl $^  > $@

temp-powerpc-debug-generic: config-powerpc-generic temp-debug-generic
	perl merge.pl $^  > $@

temp-powerpc32-generic: config-powerpc32-generic temp-powerpc-generic
	perl merge.pl $^  > $@

temp-powerpc64-generic: config-powerpc64 temp-powerpc-generic
	perl merge.pl $^ > $@

temp-s390-generic: config-s390x temp-generic
	perl merge.pl $^ > $@

$(CFG)-i686-PAE.config: config-i686-PAE temp-x86-32-generic
	perl merge.pl $^ i386 > $@

$(CFG)-i686-PAEdebug.config: config-i686-PAE temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

$(CFG)-i686.config: /dev/null temp-x86-32-generic
	perl merge.pl $^ i386 > $@

$(CFG)-i686-debug.config: /dev/null temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

$(CFG)-x86_64.config: /dev/null temp-x86_64-generic
	perl merge.pl $^ x86_64 > $@

$(CFG)-x86_64-debug.config: /dev/null temp-x86_64-debug-generic
	perl merge.pl $^ x86_64 > $@

$(CFG)-ppc64.config: /dev/null temp-powerpc64-generic
	perl merge.pl $^ powerpc > $@

$(CFG)-ppc64-debug.config: temp-powerpc64-generic temp-powerpc-debug-generic
	perl merge.pl $^ powerpc > $@

$(CFG)-ppc64p7.config: config-powerpc64p7 temp-powerpc64-generic
	perl merge.pl $^ powerpc > $@

$(CFG)-s390x.config: config-s390x temp-s390-generic
	perl merge.pl $^ s390 > $@

$(CFG)-armv7hl.config: /dev/null temp-armv7
	perl merge.pl $^ arm > $@

$(CFG)-armv7hl-lpae.config: /dev/null temp-armv7-lpae
	perl merge.pl $^ arm > $@

$(CFG)-aarch64.config: /dev/null temp-arm64
	perl merge.pl $^ arm64 > $@

$(CFG)-ppc.config: /dev/null temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@

$(CFG)-ppc-smp.config: config-powerpc32-smp temp-powerpc32-generic
	perl merge.pl $^ powerpc > $@
